<?php

declare (strict_types=1);
/**
 * @license LGPLv3, http://opensource.org/licenses/LGPL-3.0
 * @copyright Aimeos (aimeos.org), 2015-2026
 * @package Controller
 * @subpackage Common
 */
namespace Aimeos\Controller\Jobs\Common\Product\Import\Csv\Processor\Catalog;

/**
 * Catalog processor for CSV imports
 *
 * @package Controller
 * @subpackage Common
 */
class Standard extends \Aimeos\Controller\Jobs\Common\Product\Import\Csv\Processor\Base implements \Aimeos\Controller\Jobs\Common\Product\Import\Csv\Processor\Iface
{
    /** controller/jobs/product/import/csv/processor/catalog/name
     * Name of the catalog processor implementation
     *
     * Use "Myname" if your class is named "\Aimeos\Controller\Jobs\Common\Product\Import\Csv\Processor\Catalog\Myname".
     * The name is case-sensitive and you should avoid camel case names like "MyName".
     *
     * @param string Last part of the processor class name
     * @since 2015.10
     */
    private \Aimeos\Controller\Jobs\Common\Product\Import\Csv\Cache\Catalog\Standard $cache;
    private ?array $list_types = null;
    /**
     * Initializes the object
     *
     * @param \Aimeos\MShop\ContextIface $context Context object
     * @param array $mapping Associative list of field position in CSV as key and domain item key as value
     * @param \Aimeos\Controller\Jobs\Common\Product\Import\Csv\Processor\Iface $object Decorated processor
     */
    public function __construct(\Aimeos\M_Shop\Context_Iface $context, array $mapping, ?\Aimeos\Controller\Jobs\Common\Product\Import\Csv\Processor\Iface $object = null)
    {
        parent::__construct($context, $mapping, $object);
        $config = $context->config();
        /** controller/jobs/product/import/csv/catalog/listtypes
         * Names of the catalog list types that are updated or removed
         *
         * Aimeos offers associated items like "bought together" catalogs that
         * are automatically generated by other job controllers. These relations
         * shouldn't normally be overwritten or deleted by default during the
         * import and this confiuration option enables you to specify the list
         * types that should be updated or removed if not available in the import
         * file.
         *
         * Contrary, if you don't generate any relations automatically in the
         * shop and want to import those relations too, you can set the option
         * to null to update all associated items.
         *
         * @param array|null List of catalog list type names or null for all
         * @since 2015.05
         * @see controller/jobs/product/import/csv/domains
         * @see controller/jobs/product/import/csv/separator
         * @see controller/jobs/product/import/csv/attribute/listtypes
         * @see controller/jobs/product/import/csv/media/listtypes
         * @see controller/jobs/product/import/csv/price/listtypes
         * @see controller/jobs/product/import/csv/product/listtypes
         * @see controller/jobs/product/import/csv/supplier/listtypes
         * @see controller/jobs/product/import/csv/text/listtypes
         */
        $default = $config->get('controller/jobs/product/import/csv/processor/catalog/listtypes', ['default', 'promotion']);
        $this->list_types = $config->get('controller/jobs/product/import/csv/catalog/listtypes', $default);
        if ($this->list_types === null) {
            $this->list_types = [];
            $manager = \Aimeos\M_Shop::create($context, 'product/lists/type');
            $search = $manager->filter()->slice(0, 0x7fffffff);
            foreach ($manager->search($search) as $item) {
                $this->list_types[$item->get_code()] = $item->get_code();
            }
        } else {
            $this->list_types = array_combine($this->list_types, $this->list_types);
        }
        $this->cache = $this->get_cache('catalog');
    }
    /**
     * Saves the catalog related data to the storage
     *
     * @param \Aimeos\MShop\Product\Item\Iface $product Product item with associated items
     * @param array $data List of CSV fields with position as key and data as value
     * @return array List of data which has not been imported
     */
    public function process(\Aimeos\M_Shop\Product\Item\Iface $product, array $data): array
    {
        $context = $this->context();
        $logger = $context->logger();
        $manager = \Aimeos\M_Shop::create($context, 'product');
        $separator = $context->config()->get('controller/jobs/product/import/csv/separator', "\n");
        $list_items = $product->get_list_items('catalog', $this->list_types, null, false);
        $pos = 0;
        foreach ($this->get_mapped_chunk($data, $this->get_mapping()) as $list) {
            if ($this->check_entry($list) === false) {
                continue;
            }
            $list_config = $this->get_list_config(trim($this->val($list, 'product.lists.config', '')));
            $listtype = trim($this->val($list, 'product.lists.type', 'default'));
            unset($list['product.lists.config']);
            $this->add_type('product/lists/type', 'catalog', $listtype);
            foreach (explode($separator, trim($this->val($list, 'catalog.code', ''))) as $code) {
                $code = trim($code);
                if (($cat_item = $this->cache->get($code)) === null) {
                    $msg = 'No catalog for code "%1$s" available when importing product with code "%2$s"';
                    $logger->warning(sprintf($msg, $code, $product->get_code()), 'import/csv/product');
                    continue;
                }
                if (($list_item = $product->get_list_item('catalog', $listtype, $cat_item->get_id())) === null) {
                    $list_item = $manager->create_list_item()->set_type($listtype);
                } else {
                    unset($list_items[$list_item->get_id()]);
                }
                $list_item = $list_item->from_array($list)->set_config($list_config)->set_position($pos++);
                $product->add_list_item('catalog', $list_item, $cat_item);
            }
        }
        $product->delete_list_items($list_items);
        return $this->object()->process($product, $data);
    }
    /**
     * Checks if an entry can be used for updating a media item
     *
     * @param array $list Associative list of key/value pairs from the mapping
     * @return bool True if valid, false if not
     */
    protected function check_entry(array $list): bool
    {
        if ($this->val($list, 'catalog.code') === null) {
            return false;
        }
        if (($type = trim($this->val($list, 'product.lists.type', 'default'))) && !isset($this->list_types[$type])) {
            $msg = sprintf('Invalid type "%1$s" (%2$s)', $type, 'product list');
            throw new \Aimeos\Controller\Jobs\Exception($msg);
        }
        return true;
    }
}